name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      AWS_REGION: us-east-1
      CDK_NEW_BOOTSTRAP: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Projen synth
        run: npx projen
      - name: Build & tests
        run: npm run build
      - name: CDK synth
        run: npx cdk synth -q
      - name: CDK diff (do not fail CI)
        run: npx cdk diff --no-color > cdk-diff.txt || true
      - name: Upload diff artifact
        uses: actions/upload-artifact@v4
        with:
          name: cdk-diff
          path: cdk-diff.txt
