name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Print env
        run: |
          node -v
          npm -v
      - name: Install deps
        run: npm ci
      - name: Projen synth
        run: npx projen
      - name: Build & tests
        run: npm run build
      - name: CDK synth
        run: npx cdk synth
      - name: CDK diff (don’t fail CI)
        run: npx cdk diff --no-color > cdk-diff.txt || true
      - uses: actions/upload-artifact@v4
        with:
          name: cdk-diff
          path: cdk-diff.txt
